version: "3"

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    ports:
      - "5434:5432"
    volumes:
      - "postgresqlData:/var/lib/postgresql/data"
    networks:
      - backend

  web:
    env_file:
      - ./.env
    entrypoint: ./entrypoint.sh
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/home/application
    networks:
      - backend
    depends_on:
      - db

  web_celery:
    # entrypoint: ./entrypoint.sh
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      - db
    command: celery -A dashboard.celery  beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/home/application
    networks:
      - backend

  web_celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      - db
    command: celery -A dashboard.celery worker -l debug
    volumes:
      - .:/home/application
    networks:
      - backend

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui
    env_file:
      - .env
    ports:
      - "81:8080"
    volumes:
      - ./doc:/usr/share/nginx/html/doc
    environment:
      API_URL: doc/openapi.yml
      HOST_BASE_URL: "localhost"

  redis:
    image: redis:latest
    networks:
      - backend


volumes:
  postgresqlData:

networks:
  backend:
