version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    ports:
      - "5434:5432"
    volumes:
      - "postgresqlData:/var/lib/postgresql/data"
  web:
    env_file:
      - ./.env
    entrypoint: ./entrypoint.sh
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/home/application
    depends_on:
      - db

  web_celery:
    # entrypoint: ./entrypoint.sh
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      - db
    command: celery -A dashboard.celery beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/home/application

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container
    env_file:
      - .env
    ports:
      - "81:8080"
    volumes:
      - ./doc:/usr/share/nginx/html/doc
    environment:
      API_URL: doc/openapi.yml
      HOST_BASE_URL: "localhost"
  redis:
    image: redis:latest

volumes:
  postgresqlData:
