# Generated by Django 4.1.2 on 2023-03-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True,)),
                ('name', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('cpu_core', models.SmallIntegerField()),
                ('ram', models.IntegerField()),
                ('disk', models.IntegerField()),
                ('rating_per_hour', models.DecimalField(
                    decimal_places=0, max_digits=10)),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
