# Generated by Django 4.1.2 on 2023-03-30 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualMachineService',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('SUSPENDED', 'SUSPENDED'), ('SHUTOFF', 'SHUTOFF'), ('UNKNOWN', 'UNKNOWN')], max_length=255)),
                ('openstack_id', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('flavor_name', models.CharField(max_length=255)),
                ('flavor_ram', models.IntegerField()),
                ('flavor_cpu', models.SmallIntegerField()),
                ('flavor_disk', models.SmallIntegerField()),
                ('flavor_rating_hourly', models.DecimalField(decimal_places=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
