# Generated by Django 4.1.2 on 2023-04-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_virtualmachineservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachineservice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
