# Generated by Django 4.1.2 on 2023-04-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_virtualmachineservice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachineservice',
            name='openstack_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
