# Generated by Django 4.1.2 on 2023-08-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_virtualmachineservice_openstack_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavor',
            name='rating_per_hour',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='price per hour'),
        ),
        migrations.AlterField(
            model_name='virtualmachineservice',
            name='id',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
