# Generated by Django 4.1.2 on 2023-08-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_flavor_rating_per_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavor',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='virtualmachineservice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
