# Generated by Django 4.1.2 on 2023-03-30 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0002_virtualmachineservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualMachineServiceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('usage_hours', models.PositiveBigIntegerField()),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.virtualmachineservice')),
            ],
        ),
    ]
