# Generated by Django 4.1.2 on 2023-04-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachineserviceusage',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='virtualmachineserviceusage',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='virtualmachineserviceusage',
            name='usage_hours',
            field=models.FloatField(null=True),
        ),
    ]
