# Generated by Django 4.1.2 on 2023-08-25 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_invoice_amount_remove_invoice_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicerecord',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_record', to='reports.invoice'),
        ),
        migrations.AlterField(
            model_name='virtualmachineserviceusage',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='virtualmachineserviceusage',
            name='usage_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
