# Generated by Django 4.1.2 on 2024-01-11 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_flavor_id_alter_virtualmachineservice_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0005_alter_invoicerecord_invoice_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'فاکتور', 'verbose_name_plural': 'فاکتورها'},
        ),
        migrations.AlterModelOptions(
            name='invoicerecord',
            options={'verbose_name': 'رکورد فاکتور', 'verbose_name_plural': 'رکوردهای فاکتور'},
        ),
        migrations.AlterModelOptions(
            name='virtualmachineserviceusage',
            options={'verbose_name': 'استفاده از سرویس ماشین مجازی', 'verbose_name_plural': 'استفاده\u200cهای سرویس ماشین مجازی'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='مهلت پرداخت'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش'),
        ),
        migrations.AddField(
            model_name='virtualmachineserviceusage',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualmachineserviceusage',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='زمان پایان'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='start_date',
            field=models.DateTimeField(verbose_name='زمان شروع'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='مجموع مبلغ'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='invoicerecord',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='invoicerecord',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_record', to='reports.invoice', verbose_name='فاکتور'),
        ),
        migrations.AlterField(
            model_name='invoicerecord',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='invoicerecord',
            name='record_type',
            field=models.CharField(choices=[('VM', 'VIRTUAL_MACHINE'), ('SNAPSHOT', 'SNAPSHOT'), ('VOLUME', 'VOLUME')], max_length=255, verbose_name='نوع رکورد'),
        ),
        migrations.AlterField(
            model_name='invoicerecord',
            name='unit_price',
            field=models.PositiveIntegerField(verbose_name='قیمت واحد'),
        ),
        migrations.AlterField(
            model_name='invoicerecord',
            name='usage',
            field=models.FloatField(verbose_name='مقدار مصرف'),
        ),
        migrations.AlterField(
            model_name='virtualmachineserviceusage',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان'),
        ),
        migrations.AlterField(
            model_name='virtualmachineserviceusage',
            name='start_date',
            field=models.DateTimeField(verbose_name='زمان شروع'),
        ),
        migrations.AlterField(
            model_name='virtualmachineserviceusage',
            name='usage_hours',
            field=models.FloatField(blank=True, null=True, verbose_name='ساعات استفاده'),
        ),
        migrations.AlterField(
            model_name='virtualmachineserviceusage',
            name='vm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.virtualmachineservice', verbose_name='سرویس ماشین مجازی'),
        ),
    ]
