# Generated by Django 3.2.23 on 2024-02-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_invoice_options_alter_invoicerecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid_date',
            field=models.DateTimeField(null=True, verbose_name='تاریخ پرداخت'),
        ),
    ]
