# Generated by Django 4.1.2 on 2024-01-11 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_userwalletrequest_created_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userwalletrequest',
            options={'verbose_name': 'درخواست افزایش شارژ کیف پول کاربر', 'verbose_name_plural': 'درخواست افزایش شارژ کیف پول کاربران'},
        ),
    ]
